#!/usr/bin/env bash
# OBSOLETE: pre-iter1 raw-sbatch cataloging driver using python39 paths.
# Superseded by submit_full_chain.sh + run_full_pipeline_<target>.sh
# (see README "Iter1 / Iter2 / Iter3 / Iter4 cataloging cycle").
# Set ALLOW_OBSOLETE=1 to bypass.
if [[ "${ALLOW_OBSOLETE:-0}" != "1" ]]; then
    echo "this code is obsolete; see README iter1-4 section" >&2
    exit 1
fi

sbatch --job-name=webb-cat-F405N-a-ds-bg --output=web-cat-F405N-a%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F405N --bgsub --desaturated --daophot --modules=nrca"
sbatch --job-name=webb-cat-F410M-a-ds-bg --output=web-cat-F410M-b%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F410M --bgsub --desaturated --daophot --modules=nrca"
sbatch --job-name=webb-cat-F466N-a-ds-bg --output=web-cat-F466N-a%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F466N --bgsub --desaturated --daophot --modules=nrca"
sbatch --job-name=webb-cat-F405N-a-ds-bg --output=web-cat-F405N-a%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F405N --bgsub --daophot --modules=nrca"
sbatch --job-name=webb-cat-F410M-a-ds-bg --output=web-cat-F410M-b%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F410M --bgsub --daophot --modules=nrca"
sbatch --job-name=webb-cat-F466N-a-ds-bg --output=web-cat-F466N-a%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F466N --bgsub --daophot --modules=nrca"

sbatch --job-name=webb-cat-F405N-b-ds-bg --output=web-cat-F405N-a%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F405N --bgsub --desaturated --daophot --modules=nrcb"
sbatch --job-name=webb-cat-F410M-b-ds-bg --output=web-cat-F410M-b%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F410M --bgsub --desaturated --daophot --modules=nrcb"
sbatch --job-name=webb-cat-F466N-b-ds-bg --output=web-cat-F466N-a%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F466N --bgsub --desaturated --daophot --modules=nrcb"
sbatch --job-name=webb-cat-F405N-b-ds-bg --output=web-cat-F405N-a%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F405N --bgsub --daophot --modules=nrca"
sbatch --job-name=webb-cat-F410M-b-ds-bg --output=web-cat-F410M-b%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F410M --bgsub --daophot --modules=nrca"
sbatch --job-name=webb-cat-F466N-b-ds-bg --output=web-cat-F466N-a%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F466N --bgsub --daophot --modules=nrcb"

sbatch --job-name=webb-cat-F187N-a-ds-bg --output=web-cat-F187N-a%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F187N --bgsub --desaturated --daophot --modules=nrca"
sbatch --job-name=webb-cat-F182M-a-ds-bg --output=web-cat-F182M-b%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F182M --bgsub --desaturated --daophot --modules=nrca"
sbatch --job-name=webb-cat-F212N-a-ds-bg --output=web-cat-F212N-a%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F212N --bgsub --desaturated --daophot --modules=nrca"
sbatch --job-name=webb-cat-F187N-a-ds-bg --output=web-cat-F187N-a%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F187N --bgsub --daophot --modules=nrca"
sbatch --job-name=webb-cat-F182M-a-ds-bg --output=web-cat-F182M-b%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F182M --bgsub --daophot --modules=nrca"
sbatch --job-name=webb-cat-F212N-a-ds-bg --output=web-cat-F212N-a%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F212N --bgsub --daophot --modules=nrca"

sbatch --job-name=webb-cat-F187N-b-ds-bg --output=web-cat-F187N-a%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F187N --bgsub --desaturated --daophot --modules=nrcb"
sbatch --job-name=webb-cat-F182M-b-ds-bg --output=web-cat-F182M-b%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F182M --bgsub --desaturated --daophot --modules=nrcb"
sbatch --job-name=webb-cat-F212N-b-ds-bg --output=web-cat-F212N-a%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F212N --bgsub --desaturated --daophot --modules=nrcb"
sbatch --job-name=webb-cat-F187N-b-ds-bg --output=web-cat-F187N-a%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F187N --bgsub --daophot --modules=nrca"
sbatch --job-name=webb-cat-F182M-b-ds-bg --output=web-cat-F182M-b%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F182M --bgsub --daophot --modules=nrca"
sbatch --job-name=webb-cat-F212N-b-ds-bg --output=web-cat-F212N-a%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=256gb --time=96:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/catalog_long.py --filternames=F212N --bgsub --daophot --modules=nrcb"

