 sbatch --job-name=co_ice_absorbance --account=astronomy-dept --qos=astronomy-dept --nodes=1 --ntasks=32 --mem=64gb --time=2:00:00 --output=/blue/adamginsburg/adamginsburg/logs/coiceabsorbance_%j.log --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python312/bin/python /orange/adamginsburg/repos/icemodels/icemodels/absorbance_in_filters.py"

 sbatch --job-name=ice_absorbance --account=astronomy-dept --qos=astronomy-dept --nodes=1 --ntasks=1 --mem=32gb --time=2:00:00 --output=/blue/adamginsburg/adamginsburg/logs/absorbances_%j.log --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python312/bin/python /orange/adamginsburg/jwst/brick/analysis/absorbance_on_filters.py"

sbatch --job-name=extvec_figs --account=astronomy-dept --qos=astronomy-dept --nodes=1 --ntasks=4 --mem=64gb --time=2:00:00 --output=/blue/adamginsburg/adamginsburg/logs/extvec_figs_%j.log --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python312/bin/python /orange/adamginsburg/jwst/brick/analysis/plot_ccd_extinction_vectors.py"
sbatch --job-name=brick_rgb_overlay --account=astronomy-dept --qos=astronomy-dept --nodes=1 --ntasks=4 --mem=64gb --time=2:00:00 --output=/blue/adamginsburg/adamginsburg/logs/brick_catalog_overlay_RGB_%j.log --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python312/bin/python /orange/adamginsburg/jwst/brick/analysis/catalog_on_RGB.py"
sbatch --job-name=isoarchivespectra --account=astronomy-dept --qos=astronomy-dept --nodes=1 --ntasks=4 --mem=64gb --time=2:00:00 --output=/blue/adamginsburg/adamginsburg/logs/isoarchivespectra_%j.log --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python312/bin/python /orange/adamginsburg/jwst/brick/analysis/ISO_Spectra.py"
sbatch --job-name=brick-ccds-cmds --output=/blue/adamginsburg/adamginsburg/logs/web-brick-cmdccd-%j.log  --account=astronomy-dept --qos=astronomy-dept-b --ntasks=8 --nodes=1 --mem=32gb --time=2:00:00 --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python312/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/analysis/make_CCDsandCMDs.py"
sbatch --job-name=co_ice_CCDs --account=astronomy-dept --qos=astronomy-dept --nodes=1 --ntasks=1 --mem=32gb --time=2:00:00 --output=/blue/adamginsburg/adamginsburg/logs/icemodel_ccds_%j.log --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python312/bin/python /orange/adamginsburg/jwst/brick/analysis/make_ccd_with_icemodels.py"
sbatch --job-name=brickfig9a --account=astronomy-dept --qos=astronomy-dept --nodes=1 --ntasks=4 --mem=64gb --time=2:00:00 --output=/blue/adamginsburg/adamginsburg/logs/brickfig9_%j.log --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python312/bin/python /orange/adamginsburg/jwst/brick/analysis/make_icecolumn_fig9.py"
sbatch --job-name=jwstarchivespectra --account=astronomy-dept --qos=astronomy-dept --nodes=1 --ntasks=4 --mem=64gb --time=2:00:00 --output=/blue/adamginsburg/adamginsburg/logs/jwstarchivespectra_%j.log --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python312/bin/python /orange/adamginsburg/jwst/brick/analysis/JWST_Archive_Spectra.py"
sbatch --job-name=icecolumn_vs_av --account=astronomy-dept --qos=astronomy-dept --nodes=1 --ntasks=4 --mem=32gb --time=2:00:00 --output=/blue/adamginsburg/adamginsburg/logs/icecolumn_vs_av_%j.log --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python312/bin/python /orange/adamginsburg/jwst/brick/analysis/icecolumn_vs_av.py"
sbatch --job-name=icecolumn_map --account=astronomy-dept --qos=astronomy-dept --nodes=1 --ntasks=4 --mem=32gb --time=2:00:00 --output=/blue/adamginsburg/adamginsburg/logs/icecolumn_map_%j.log --wrap "/blue/adamginsburg/adamginsburg/miniconda3/envs/python312/bin/python /orange/adamginsburg/jwst/brick/analysis/icecolumn_map.py"